apiVersion: v1
kind: Service
metadata:
  name: { { .Chart.name } }-nodeport
  namespace: { { .Values.common.namespace } }
spec:
  type: NodePort
  selector:
    app: { { .Chart.name } }
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
